# Generated by Django 4.2.27 on 2026-01-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipe',
            new_name='content',
        ),
    ]
