# Generated by Django 4.2.27 on 2026-01-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
