# Generated by Django 4.2.27 on 2026-01-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_excerpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
