# Generated by Django 4.2.27 on 2026-01-13 10:59

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
