# Generated by Django 4.2.27 on 2026-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
